

services:

  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    # ports:
      # - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the Collector
      # - 8889:8889 # Prometheus exporter metrics
      # - 13133:13133 # health_check extension
      # - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension
    depends_on:
      - jaeger
    networks:
      - poc-tracing

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 16686:16686
      # - 4317:4317
      # - 4318:4318
      # - 5778:5778
      # - 9411:9411
    networks:
      - poc-tracing

  app:
    build:
      dockerfile: dockerfile
    container_name: app
    ports:
      - "3333:3333"
    environment:
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      # - OTEL_SERVICE_NAME
      # - OTEL_SERVICE_VERSION
      # - OTEL_RESOURCE_ATTRIBUTES
    networks:
      - poc-tracing
    depends_on:
      - collector

networks:
  poc-tracing:
    driver: bridge